{% set name = "drf-dynamic-fields" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/drf_dynamic_fields-{{ version }}.tar.gz
  sha256: f20a5ec27d003db7595c9315db22217493dcaed575f3811d3e12f264c791c20c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django

test:
  imports:
    - drf_dynamic_fields
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dbrgn/drf-dynamic-fields
  summary: Dynamically return subset of Django REST Framework serializer fields
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
